version: '3.8'

services:
  streamlit-app:
    build:
      context: ..
      dockerfile: devops/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../app:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: always
